# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sf-remix-app-aws-template"
client_id = "a5cd51a3cf53166a6ab580a51ec06ffb"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
